Add pre_build phase in copilot buildspec to skip copilot steps when service-deployment-mode is platform

diff --git a/terraform/codebase-pipelines/buildspec-deploy-copilot.yml b/terraform/codebase-pipelines/buildspec-deploy-copilot.yml
--- a/terraform/codebase-pipelines/buildspec-deploy-copilot.yml
+++ b/terraform/codebase-pipelines/buildspec-deploy-copilot.yml
@@ -38,10 +38,50 @@ phases:
       - pip install yq --quiet
       ## Install platform helper
       - ./terraform/scripts/install_platform_helper.sh
+  
+  pre_build:
+    commands:
+      # Check service-deployment-mode and exit early if value doesn't correspond
+      - |
+        ENVIRONMENT="${ENVIRONMENT}"
+        PLATFORM_CONFIG_PATH="${CODEBUILD_SRC_DIR}/platform-config.yml"
+        ALLOWED_MODES=("dual-deploy-copilot-traffic" "dual-deploy-platform-traffic" "copilot")
+
+        DEPLOY_MODE=$(yq eval ".environments.\"$ENVIRONMENT\".service-deployment-mode" "$PLATFORM_CONFIG_PATH")
+
+        if [ "$DEPLOY_MODE" == "null" ] || [ -z "$DEPLOY_MODE" ]; then
+          DEPLOY_MODE=$(yq eval '.environments."*".service-deployment-mode' "$PLATFORM_CONFIG_PATH")
+          if [ "$DEPLOY_MODE" == "null" ] || [ -z "$DEPLOY_MODE" ]; then
+            echo "Property 'service-deployment-mode' not found in platform-config. No further action required, skipping pipeline stage ..."
+            export SKIP_BUILD="true"
+          fi
+        fi
+
+        MATCHED=false
+        for mode in "${ALLOWED_MODES[@]}"; do
+          if [[ "$DEPLOY_MODE" == "$mode" ]]; then
+            MATCHED=true
+            break
+          fi
+        done
+
+        if [ "$MATCHED" == "false" ]; then
+          echo "Detected default service-deployment-mode. No further action required, skipping pipeline stage ..."
+          export SKIP_BUILD="true"
+        else
+          echo "Property service-deployment-mode '$DEPLOY_MODE' detected. Resuming pipeline ..."
+        fi
 
   build:
     commands:
-      - set -e
+      - |
+        set -e
+        
+        # Skip pipeline if true
+        if [[ "$SKIP_BUILD" == "true" ]]; then
+          echo "Skipping pipeline stage, no further action required."
+          exit 0
+        fi
 
       # Check if the specified image tag exists
       - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
