Pass DNS_ACCOUNT_ID into codebuild project

diff --git a/terraform/codebase-pipelines/buildspec-invalidate-cache.yml b/terraform/codebase-pipelines/buildspec-invalidate-cache.yml
--- a/terraform/codebase-pipelines/buildspec-invalidate-cache.yml
+++ b/terraform/codebase-pipelines/buildspec-invalidate-cache.yml
@@ -12,29 +12,44 @@ phases:
 
   build:
     commands:
-      # Need to find out how many distributions should be touched
-      - set -e
-      - CONFIG_JSON='"{\"web.kate.demodjango.uktrade.digital\":[\"/hello/*\", \"/goodbye/*\"], \"api.kate.demodjango.uktrade.digital\":[\"/hello/*\", \"/goodbye/*\"]}"'
-      # - CDN_ACCOUNT_ID=""
-      
-      # Assume cdn account role
-      - account_id=$(echo ${ENV_CONFIG} | jq -r '.accounts | .dns.id'
-      - echo -e "\nAssume role in ${account_id} account"
-      - assumed_role=$(aws sts assume-role --role-arn "arn:aws:iam::${CDN_ACCOUNT_ID}:role/environment-pipeline-assumed-role" --role-session-name "${APPLICATION}-${ENVIRONMENT}-cdn-cache-invalidation")
-      - export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
-      - export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
-      - export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
-      
-      # Invalidate caches
       - |
-          DOMAINS=$(echo $CONFIG_JSON | jq -r 'fromjson | keys[]')
-          for i in ${DOMAINS}; do
-            echo "Getting distribution ID for domain ${i}"
-            DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items' --output json | jq -r --arg domain "$i" '.[] | select(.Aliases.Items != null and .Aliases.Items[0] == $domain) | .Id')
-            PATHS=$(echo $CONFIG_JSON | jq -r --arg domain ${i} 'fromjson | .[$domain] | join(" ")')
-            echo -e "\nInvalidating the cache in distibution id ${DISTRIBUTION_ID} for paths ${PATHS}\n"
-          done
-
+        set -e
+        CONFIG_JSON='"{\"web.kate.demodjango.uktrade.digital\":[\"/hello/*\", \"/goodbye/*\"], \"api.kate.demodjango.uktrade.digital\":[\"/hello/*\", \"/goodbye/*\"]}"'
+        
+        echo -e "\nAssume role in ${DNS_ACCOUNT_ID} account"
+        assumed_role=$(aws sts assume-role --role-arn "arn:aws:iam::${DNS_ACCOUNT_ID}:role/environment-pipeline-assumed-role" --role-session-name "${APPLICATION}-${ENVIRONMENT}-cdn-cache-invalidation")
+        export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
+        export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
+        export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
+      
+        # Invalidate caches
+        DOMAINS=$(echo $CONFIG_JSON | jq -r 'fromjson | keys[]')
+        for i in ${DOMAINS}; do
+          echo "Getting distribution ID for domain ${i}"
+          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items' --output json | jq -r --arg domain "$i" '.[] | select(.Aliases.Items != null and .Aliases.Items[0] == $domain) | .Id')
+          PATHS=$(echo $CONFIG_JSON | jq -r --arg domain ${i} 'fromjson | .[$domain] | join(" ")')
+          echo -e "\nInvalidating the cache in distibution id ${DISTRIBUTION_ID} for paths ${PATHS}\n"
+        done
+      #TODO check for any alias=domain, instead of just the first item
   post_build:
     commands:
       - echo "DONE"
+
+build:
+    commands:
+    - |
+      # Need to find out how many distributions should be touched
+      set -e
+      echo "Running invalidation"
+      CONFIG_JSON='"{\"web.kate.demodjango.uktrade.digital\":[\"/hello/*\", \"/goodbye/*\"], \"api.kate.demodjango.uktrade.digital\":[\"/hello/*\", \"/goodbye/*\"]}"'
+      echo "CONFIG_JSON: $CONFIG_JSON"
+      DOMAINS=$(echo $CONFIG_JSON | jq -r 'fromjson | keys[]')
+      echo "DOMAINS: $DOMAINS"
+      for i in ${DOMAINS}; do
+        echo "Getting distribution ID for domain ${i}"
+        echo $AWS_PROFILE
+        aws cloudfront list-distributions --query 'DistributionList.Items' --output json | jq -r --arg domain "$i" '.[] | select(.Aliases.Items != null and .Aliases.Items[0] == $domain) | .Id'
+        DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items' --output json | jq -r --arg domain "$i" '.[] | select(.Aliases.Items != null and .Aliases.Items[0] == $domain) | .Id')
+        PATHS=$(echo $CONFIG | jq -r --arg domain "$i" 'fromjson | .[$domain] | join(" ")')
+        echo -e "\nInvalidating the cache in distibution id ${DISTRIBUTION_ID} for paths ${PATHS}\n"
+      done
