add application name to condition values

diff --git a/terraform/codebase-pipelines/buildspec-terraform-deploy.yml b/terraform/codebase-pipelines/buildspec-terraform-deploy.yml
--- a/terraform/codebase-pipelines/buildspec-terraform-deploy.yml
+++ b/terraform/codebase-pipelines/buildspec-terraform-deploy.yml
@@ -142,8 +142,8 @@ phases:
 
           # Send deployment starting Slack notification
           
-          MESSAGE=":rocket: STARTED - Deployment of tag \`${DEPLOY_TAG}\` to service \`${SERVICE}\` for environment \`${ENVIRONMENT}\` <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution>"
-          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
+          # MESSAGE=":rocket: STARTED - Deployment of tag \`${DEPLOY_TAG}\` to service \`${SERVICE}\` for environment \`${ENVIRONMENT}\` <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution>"
+          # platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
 
           # Assume environment role
         
@@ -164,25 +164,25 @@ phases:
 
           # Send Slack message on pipeline outcome
           
-           if [ $? -eq 0 ]; then
-             deploy_status="SUCCESSFUL"
-             STATUS_EMOJI=":large_green_circle:"
-             STATUS_TEXT="COMPLETE"
-           else
-             deploy_status="FAILED"
-             STATUS_EMOJI=":red_circle::warning:"
-             STATUS_TEXT="FAILED"
-           fi
+          #  if [ $? -eq 0 ]; then
+          #    deploy_status="SUCCESSFUL"
+          #    STATUS_EMOJI=":large_green_circle:"
+          #    STATUS_TEXT="COMPLETE"
+          #  else
+          #    deploy_status="FAILED"
+          #    STATUS_EMOJI=":red_circle::warning:"
+          #    STATUS_TEXT="FAILED"
+          #  fi
 
-          # Send notification on successful deployment or exit with an error code
+          # # Send notification on successful deployment or exit with an error code
         
-           if [ "${deploy_status}" == "SUCCESSFUL" ]; then
-             MESSAGE="${STATUS_EMOJI} ${STATUS_TEXT} - Deployment of tag \`${DEPLOY_TAG}\` to service \`${SERVICE}\` for environment \`${ENVIRONMENT}\` <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution>"
-             platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
-           else
-             echo "Error: Deployment status is ${deploy_status}" | tee output.log
-             exit 1
-           fi
+          #  if [ "${deploy_status}" == "SUCCESSFUL" ]; then
+          #    MESSAGE="${STATUS_EMOJI} ${STATUS_TEXT} - Deployment of tag \`${DEPLOY_TAG}\` to service \`${SERVICE}\` for environment \`${ENVIRONMENT}\` <https://${AWS_REGION}.console.aws.amazon.com/codesuite/codebuild/${AWS_ACCOUNT_ID}/projects/${BUILD_ID_PREFIX}/build/${CODEBUILD_BUILD_ID}/?region=${AWS_REGION}|Build log> | <${PIPELINE_EXECUTION_URL}|Pipeline execution>"
+          #    platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
+          #  else
+          #    echo "Error: Deployment status is ${deploy_status}" | tee output.log
+          #    exit 1
+          #  fi
         fi
 
   post_build:
