sync-tpm.sh

diff --git a/terraform/codebase-pipelines/buildspec-deploy.yml b/terraform/codebase-pipelines/buildspec-deploy.yml
--- a/terraform/codebase-pipelines/buildspec-deploy.yml
+++ b/terraform/codebase-pipelines/buildspec-deploy.yml
@@ -9,6 +9,12 @@ env:
 phases:
   install:
     commands:
+      - COPILOT_VERSION=`cat .copilot-version`
+      - curl -s -qL -o copilot-binary https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v${COPILOT_VERSION}
+      - chmod +x copilot-binary
+      - mkdir -p /codebuild/bin
+      - mv copilot-binary /codebuild/bin/copilot
+      - export PATH=$PATH:/codebuild/bin
       - pip install yq dbt-platform-helper --quiet
       - curl -s -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > /usr/local/bin/regctl
       - chmod +x /usr/local/bin/regctl
@@ -61,10 +67,8 @@ phases:
 
       - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
 
-      # Build image uri
-      - task_family="${APPLICATION}-${ENVIRONMENT}-${SERVICE}"
-      - cluster="${APPLICATION}-${ENVIRONMENT}"
-      - image_uri="${REPOSITORY_URL}:${IMAGE_TAG}"
+      # Run Copilot package command and clean the manifest output
+      - copilot svc package --env "${ENVIRONMENT}" --name "${SERVICE}" | yq .Metadata.Manifest | jq -r . | yq 'del(.image.location)' > new.yml
 
       # Assume environment role
       - account_id=$(echo ${ENV_CONFIG} | jq -c -r .${ENVIRONMENT}.account)
@@ -73,94 +77,110 @@ phases:
       - export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
       - export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
 
-      # Get service name
-      - service_name=$(aws ecs list-services --cluster "${cluster}" | jq -r '.serviceArns[] | select(test("'${cluster}'-'${SERVICE}'($|-Service.*)"))' | cut -d '/' -f3)
-
-      # Update task definition
-      - task_definition=$(aws ecs describe-task-definition --task-definition "${task_family}")
-      - new_task_definition=$(echo ${task_definition} | jq '.taskDefinition | .containerDefinitions |= map(if .name == '\"${SERVICE}\"' then .image = '\"${image_uri}\"' else . end) | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) |  del(.registeredAt)  | del(.registeredBy)')
-      - new_task_info=$(aws ecs register-task-definition --cli-input-json "${new_task_definition}")
-      - new_revision=$(echo ${new_task_info} | jq '.taskDefinition.revision')
-
-      # Get desired task count
-      - count=0
-      - cd "${CODEBUILD_SRC_DIR}"
-
-      # If count is a range, get the first value otherwise get count
+      # Get the current CloudFormation template and clean it for comparison
+      - aws cloudformation get-template --stack-name "${APPLICATION}-${ENVIRONMENT}-${SERVICE}" --output json --query TemplateBody | jq -r . | yq .Metadata.Manifest | jq -r . | yq 'del(.image.location)' > current.yml
+  
+      - diff new.yml current.yml; DIFF_EXIT_CODE=$?
+      - echo "DIFF EXIT CODE IS ${DIFF_EXIT_CODE}"
+      
       - |
-        if [ $(yq '.count | type == "object"' copilot/${SERVICE}/manifest.yml) == "true" ]; then
-          count=$(yq '.count.range' copilot/${SERVICE}/manifest.yml | tr -d '"' | cut -d '-' -f1)
-        else
-          count=$(yq '.count' copilot/${SERVICE}/manifest.yml)
-        fi
+        if [[ $DIFF_EXIT_CODE -ne 0 ]]; then
+          echo "Differences detected between deployed and committed service templates, running copilot svc deploy..."
 
-      # Check for environment overrides
-      - |
-        if [ $(yq '.environments.'${ENVIRONMENT}'.count | type == "object"' copilot/${SERVICE}/manifest.yml) == "true" ]; then
-          env_count=$(yq '.environments.'${ENVIRONMENT}'.count.range' copilot/${SERVICE}/manifest.yml | tr -d '"' | cut -d '-' -f1)
-        else
-          env_count=$(yq '.environments.'${ENVIRONMENT}'.count' copilot/${SERVICE}/manifest.yml)
-        fi
-
-      - |
-        if [[ "${env_count}" != "null" ]]; then
-          count=${env_count}
-        fi
-
-      # Start deployment
-      - echo "Deploying ${image_uri} to ${service_name} in ${cluster} with task count ${count}"
-      - start=$( date +%s )
-      - deploy_status="IN_PROGRESS"
-      - aws ecs update-service --cluster "${cluster}" --service "${service_name}" --task-definition "${task_family}:${new_revision}" --desired-count ${count} > /dev/null 2>&1
-
-      # Check deployment status
-      - |
-        while [[ "${deploy_status}" == "IN_PROGRESS" || "${deploy_status}" == "PENDING" || "${deploy_status}" == "ROLLBACK_IN_PROGRESS" || "${deploy_status}" == "null" ]];
-        do
-          sleep 10
-          now=$( date +%s )
-          elapsed=$(( now-start ))
-
-          deploy_status=$(aws ecs list-service-deployments --cluster "${cluster}" --service "${service_name}" --created-at "after=${start}" | jq -r '.serviceDeployments[0].status')
+          unset AWS_ACCESS_KEY_ID
+          unset AWS_SECRET_ACCESS_KEY
+          unset AWS_SESSION_TOKEN
         
-          if [[ "${deploy_status}" == "null" ]]; then deploy_status="PENDING"; fi
-          echo "Deployment status after ${elapsed} seconds: ${deploy_status}"
+          copilot svc deploy --env "${ENVIRONMENT}" --name "${SERVICE}"
+        else
+          # Build image URI
+          task_family="${APPLICATION}-${ENVIRONMENT}-${SERVICE}"
+          cluster="${APPLICATION}-${ENVIRONMENT}"
+          image_uri="${REPOSITORY_URL}:${IMAGE_TAG}"
+        
+          # Get service name
+          service_name=$(aws ecs list-services --cluster "${cluster}" | jq -r '.serviceArns[] | select(test("'${cluster}'-'${SERVICE}'($|-Service.*)"))' | cut -d '/' -f3)
+        
+          # Update task definition
+          task_definition=$(aws ecs describe-task-definition --task-definition "${task_family}")
+          new_task_definition=$(echo ${task_definition} | jq '.taskDefinition | .containerDefinitions |= map(if .name == '\"${SERVICE}\"' then .image = '\"${image_uri}\"' else . end) | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) |  del(.registeredAt)  | del(.registeredBy)')
+          new_task_info=$(aws ecs register-task-definition --cli-input-json "${new_task_definition}")
+          new_revision=$(echo ${new_task_info} | jq '.taskDefinition.revision')
 
-          if [[ ${elapsed} -gt ${DEPLOY_TIMEOUT} ]]; then
-            echo "Error: Deployment not completed within ${DEPLOY_TIMEOUT} seconds timeout" | tee output.log
+          # Get desired task count
+          count=0
+          cd "${CODEBUILD_SRC_DIR}"
+
+          # If count is a range, get the first value otherwise get count
+          if [ $(yq '.count | type == "object"' copilot/${SERVICE}/manifest.yml) == "true" ]; then
+            count=$(yq '.count.range' copilot/${SERVICE}/manifest.yml | tr -d '"' | cut -d '-' -f1)
+          else
+            count=$(yq '.count' copilot/${SERVICE}/manifest.yml)
+          fi
+
+          # Check for environment overrides
+          if [ $(yq '.environments.'${ENVIRONMENT}'.count | type == "object"' copilot/${SERVICE}/manifest.yml) == "true" ]; then
+            env_count=$(yq '.environments.'${ENVIRONMENT}'.count.range' copilot/${SERVICE}/manifest.yml | tr -d '"' | cut -d '-' -f1)
+          else
+            env_count=$(yq '.environments.'${ENVIRONMENT}'.count' copilot/${SERVICE}/manifest.yml)
+          fi
+
+          if [[ "${env_count}" != "null" ]]; then
+            count=${env_count}
+          fi
+
+          # Start deployment
+          echo "Deploying ${image_uri} to ${service_name} in ${cluster} with task count ${count}"
+          start=$( date +%s )
+          deploy_status="IN_PROGRESS"
+          aws ecs update-service --cluster "${cluster}" --service "${service_name}" --task-definition "${task_family}:${new_revision}" --desired-count ${count} > /dev/null 2>&1
+
+          # Check deployment status
+          while [[ "${deploy_status}" == "IN_PROGRESS" || "${deploy_status}" == "PENDING" || "${deploy_status}" == "ROLLBACK_IN_PROGRESS" || "${deploy_status}" == "null" ]];
+          do
+            sleep 10
+            now=$( date +%s )
+            elapsed=$(( now-start ))
+
+            deploy_status=$(aws ecs list-service-deployments --cluster "${cluster}" --service "${service_name}" --created-at "after=${start}" | jq -r '.serviceDeployments[0].status')
+          
+            if [[ "${deploy_status}" == "null" ]]; then deploy_status="PENDING"; fi
+            echo "Deployment status after ${elapsed} seconds: ${deploy_status}"
+
+            if [[ ${elapsed} -gt ${DEPLOY_TIMEOUT} ]]; then
+              echo "Error: Deployment not completed within ${DEPLOY_TIMEOUT} seconds timeout" | tee output.log
+              exit 1
+            fi
+          done
+
+          # Check deployment success
+          case "${deploy_status}" in
+            SUCCESSFUL)
+              STATUS_EMOJI=":large_green_circle:"
+              STATUS_TEXT="COMPLETE"
+              ;;
+            ROLLBACK_SUCCESSFUL)
+              STATUS_EMOJI=":red_circle:"
+              STATUS_TEXT="FAILED"
+              ;;
+            ROLLBACK_FAILED)
+              STATUS_EMOJI=":red_circle::warning:"
+              STATUS_TEXT="FAILED"
+              ;;
+            *)
+              STATUS_EMOJI=":large_blue_circle:"
+              STATUS_TEXT="STOP_REQUESTED/STOPPED/PENDING/IN_PROGRESS"
+              ;;
+          esac
+
+          # Send notification on successful deployment or exit with an error code
+          if [ "${deploy_status}" == "SUCCESSFUL" ]; then
+            MESSAGE="${STATUS_EMOJI} ${STATUS_TEXT} - Deployment of ${UPPERCASE_TAG} to ${UPPERCASE_SERVICE} service - ${deploy_status} - <${PIPELINE_EXECUTION_URL}|Pipeline execution url>"
+            platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
+          else
+            echo "Error: Deployment status is ${deploy_status}" | tee output.log
             exit 1
           fi
-        done
-
-      # Check deployment success
-      - |
-        case "${deploy_status}" in
-          SUCCESSFUL)
-            STATUS_EMOJI=":large_green_circle:"
-            STATUS_TEXT="COMPLETE"
-            ;;
-          ROLLBACK_SUCCESSFUL)
-            STATUS_EMOJI=":red_circle:"
-            STATUS_TEXT="FAILED"
-            ;;
-          ROLLBACK_FAILED)
-            STATUS_EMOJI=":red_circle::warning:"
-            STATUS_TEXT="FAILED"
-            ;;
-          *)
-            STATUS_EMOJI=":large_blue_circle:"
-            STATUS_TEXT="STOP_REQUESTED/STOPPED/PENDING/IN_PROGRESS"
-            ;;
-        esac
-
-      # Send notification on successful deployment or exit with an error code
-      - |
-        if [ "${deploy_status}" == "SUCCESSFUL" ]; then
-          MESSAGE="${STATUS_EMOJI} ${STATUS_TEXT} - Deployment of ${UPPERCASE_TAG} to ${UPPERCASE_SERVICE} service - ${deploy_status} - <${PIPELINE_EXECUTION_URL}|Pipeline execution url>"
-          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "${MESSAGE}"
-        else
-          echo "Error: Deployment status is ${deploy_status}" | tee output.log
-          exit 1
         fi
 
   post_build:
