revert error formatting and separate some commands to reduce output

diff --git a/terraform/codebase-pipelines/buildspec-invalidate-cache.yml b/terraform/codebase-pipelines/buildspec-invalidate-cache.yml
--- a/terraform/codebase-pipelines/buildspec-invalidate-cache.yml
+++ b/terraform/codebase-pipelines/buildspec-invalidate-cache.yml
@@ -12,40 +12,36 @@ phases:
 
   build:
     commands:
+      - set -e
       - export DNS_ACCOUNT_ID=$(echo ${ENV_CONFIG} | jq -r --arg env ${ENVIRONMENT} '.[$env].dns_account')
       - export ACCOUNT_ID=$(echo ${ENV_CONFIG} | jq -r --arg env ${ENVIRONMENT} '.[$env].account')
-      - |
-        set -e
-
-        echo -e "\nAssume role in ${DNS_ACCOUNT_ID} account"
-        assumed_role=$(aws sts assume-role --role-arn "arn:aws:iam::${DNS_ACCOUNT_ID}:role/cloudfront-invalidation-assumed-role" --role-session-name "${APPLICATION}-${ENVIRONMENT}-cdn-cache-invalidation")
-        export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
-        export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
-        export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
+      - export ENV_CACHE_INVALIDATION_CONFIG=$(echo $CONFIG_JSON | jq -r --arg env ${ENVIRONMENT} '.[$env]')
+      - export DOMAINS=$(echo $ENV_CACHE_INVALIDATION_CONFIG | jq -r 'keys[]')
+      - echo -e "\nAssume role in ${DNS_ACCOUNT_ID} account"
+      - assumed_role=$(aws sts assume-role --role-arn "arn:aws:iam::${DNS_ACCOUNT_ID}:role/cloudfront-invalidation-assumed-role" --role-session-name "${APPLICATION}-${ENVIRONMENT}-cdn-cache-invalidation")
+      - export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
+      - export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
+      - export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
       
-        # Invalidate caches
-        ENV_CACHE_INVALIDATION_CONFIG=$(echo $CONFIG_JSON | jq -r --arg env ${ENVIRONMENT} '.[$env]')
-        DOMAINS=$(echo $ENV_CACHE_INVALIDATION_CONFIG | jq -r 'keys[]')
-
+      - |
         for i in ${DOMAINS}; do
           echo "Getting distribution ID for domain ${i}"
           DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items' --output json | jq -r --arg domain "$i" '.[] | select(.Aliases.Items != null and .Aliases.Items[0] == $domain) | .Id')
           PATHS=$(echo $ENV_CACHE_INVALIDATION_CONFIG | jq -r --arg domain "${i}" '.[$domain] | map(@sh) | join(" ")')
           
           if [ -z ${DISTRIBUTION_ID} ]; then
-            echo " ERROR: No distribution ID found for domain ${i} in account ${DNS_ACCOUNT_ID}.  Please check cache_invalidation configuration.  Exiting."
+            echo "ERROR: No distribution ID found for domain ${i} in account ${DNS_ACCOUNT_ID}.  Please check cache_invalidation configuration.  Exiting."
             exit 1
           fi
           
-          echo -e "\n Running command: Invalidating the cache in distibution id ${DISTRIBUTION_ID} for paths ${PATHS}\n"
+          echo -e "\nInvalidating the cache in distibution id ${DISTRIBUTION_ID} for paths ${PATHS}\n"
           
           start=$( date +%s )
           cache_status="NotRun"
-          export DISTRIBUTION_ID="fooooo"
           invalidation_id=$(eval "aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths ${PATHS}" | jq -r ."Invalidation.Id")
           
           if [ -z ${invalidation_id} ]; then
-            echo " ERROR: Cache invalidation failed for distribution ${DISTRIBUTION_ID}.  Exiting."
+            echo "ERROR: Cache invalidation failed for distribution ${DISTRIBUTION_ID}.  Exiting."
             exit 1
           fi
           
