fix: Various bug fixes around removing Copilot (DBTP-2469) (#1114)
Co-authored-by: John Stainsby <john.stainsby@digital.trade.gov.uk>

diff --git a/terraform/environment-pipelines/buildspec-apply.yml b/terraform/environment-pipelines/buildspec-apply.yml
--- a/terraform/environment-pipelines/buildspec-apply.yml
+++ b/terraform/environment-pipelines/buildspec-apply.yml
@@ -12,17 +12,35 @@ phases:
       ## yq for yaml processing (The Go-based variant, not Python-based)
       - curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
       - chmod +x /usr/local/bin/yq
+      - |
+        DEPLOY_MODE=$(yq eval ".environments.\"${ENVIRONMENT}\".service-deployment-mode" "${CODEBUILD_SRC_DIR}/platform-config.yml")
+        if [ "$DEPLOY_MODE" == "null" ] || [ -z "$DEPLOY_MODE" ]; then
+          DEPLOY_MODE=$(yq eval ".environments."*".service-deployment-mode" "${CODEBUILD_SRC_DIR}/platform-config.yml")
+        fi
+        
+        if [ "$DEPLOY_MODE" != "platform" ]; then
+          if [ ! -f .copilot-version ]; then
+            echo "Cannot find .copilot-version file"
+            exit 1
+          fi
+          COPILOT_VERSION=`cat .copilot-version`
+          cd "${CODEBUILD_SRC_DIR}/build-tools/bin"
+          curl -s -qL -o copilot https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v"$COPILOT_VERSION"
+          chmod +x copilot
+        fi
+        
+        export DEPLOY_MODE="$DEPLOY_MODE"
+
   build:
     commands:
       - set -e
       - echo -e "\nTerraform Apply Phase"
       - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Starting terraform apply phase for the ${ENVIRONMENT} environment."
       - echo -e "\nWorking on environment ${ENVIRONMENT}"
-      - cd "terraform/environments/${ENVIRONMENT}"
+      - cd "${CODEBUILD_SRC_DIR}/terraform/environments/${ENVIRONMENT}"
       - terraform apply plan.tfplan
       - |
-        DEPLOY_MODE=$(yq eval ".environments.\"$ENVIRONMENT\".service-deployment-mode" "${CODEBUILD_SRC_DIR}/platform-config.yml")
-        if [[ "$DEPLOY_MODE" == "platform" ]]; then
+        if [[ "${DEPLOY_MODE}" == "platform" ]]; then
           echo -e "\nDeployment mode is 'platform', skipping copilot environment deploy"
         else
           echo -e "\nGenerating manifests and deploying AWS Copilot environment resources"
